version: '3.1'

services:
  db:
    image: mysql
    container_name: devbook
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - devbook_data:/var/lib/mysql

volumes:
  devbook_data: